import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { formatDate } from "@/lib/utils";

export async function POST(req: Request) {
  try {
    const supabase = createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "UNAUTHENTICATED", message: "Please log in to check in." }, { status: 401 });
    }

    const admin = createAdminClient();
    const body = await req.json().catch(() => ({}));
    const { code } = body;

    if (!code || typeof code !== "string") {
      return NextResponse.json({ error: "MISSING_CODE", message: "Gym QR code is required." }, { status: 400 });
    }

    // 1. Authoritatively validate gym by qr_code_token
    const { data: gym } = await admin
      .from("gyms")
      .select("id, name, qr_code_token, timezone")
      .eq("qr_code_token", code.trim())
      .maybeSingle();

    if (!gym) {
      return NextResponse.json(
        {
          error: "INVALID_QR_CODE",
          message: "This attendance QR code is invalid or has been regenerated by gym management.",
        },
        { status: 404 }
      );
    }

    // 2. Authoritatively fetch authenticated Member record
    const { data: member } = await admin
      .from("members")
      .select(`
        id,
        gym_id,
        status,
        member_type,
        membership_expiry,
        profiles (full_name)
      `)
      .eq("profile_id", user.id)
      .maybeSingle();

    if (!member) {
      return NextResponse.json(
        {
          error: "NOT_A_MEMBER",
          message: "No athlete membership profile associated with this login. Please see gym desk.",
        },
        { status: 403 }
      );
    }

    // 3. Multi-tenant validation: verify member belongs to this gym
    if (member.gym_id !== gym.id) {
      return NextResponse.json(
        {
          error: "WRONG_GYM",
          message: `Your membership is registered with another facility, not ${gym.name}.`,
        },
        { status: 403 }
      );
    }

    // 4. Business rule validation: membership status and validity
    const today = new Date().toISOString().split("T")[0];

    if (member.status !== "ACTIVE") {
      return NextResponse.json(
        {
          error: "INACTIVE_MEMBERSHIP",
          message: "Your membership account is currently paused or inactive. Please contact the front desk.",
        },
        { status: 403 }
      );
    }

    if (member.membership_expiry && member.membership_expiry < today) {
      return NextResponse.json(
        {
          error: "MEMBERSHIP_EXPIRED",
          message: `Your gym membership expired on ${formatDate(member.membership_expiry)}. Please renew your dues online or at reception to check in.`,
          expiryDate: member.membership_expiry,
        },
        { status: 402 }
      );
    }

    // 5. Query today's workout split for immediate post-check-in floor experience
    let todayWorkout: any = null;
    const { data: existingSched } = await admin
      .from("workout_schedules")
      .select("id, title, day_name, exercises, status")
      .eq("member_id", member.id)
      .eq("workout_date", today)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();

    if (existingSched) {
      todayWorkout = existingSched;
      // If was previously marked MISSED because of earlier absence, recover to SCHEDULED!
      if (existingSched.status === "MISSED") {
        await admin
          .from("workout_schedules")
          .update({ status: "SCHEDULED", updated_at: new Date().toISOString() })
          .eq("id", existingSched.id);
        todayWorkout.status = "SCHEDULED";
      }
    } else {
      // Auto-provision from active workout_plans
      const { data: plan } = await admin
        .from("workout_plans")
        .select("*")
        .eq("member_id", member.id)
        .eq("status", "ACTIVE")
        .maybeSingle();

      if (plan?.days && Array.isArray(plan.days)) {
        const dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
        const currentDayName = dayNames[new Date().getDay()];
        const routine = plan.days.find((d: any) => d.day?.toLowerCase() === currentDayName.toLowerCase()) || plan.days[0];

        if (routine && routine.exercises?.length > 0) {
          const { data: provisioned } = await admin
            .from("workout_schedules")
            .insert({
              gym_id: gym.id,
              member_id: member.id,
              plan_id: plan.id,
              trainer_id: plan.trainer_id,
              workout_date: today,
              day_name: routine.day || currentDayName,
              title: routine.focus || "Daily Workout Routine",
              exercises: routine.exercises,
              status: "SCHEDULED",
              completed_exercises: [],
            })
            .select()
            .single();

          todayWorkout = provisioned;
        }
      }
    }

    // 6. Duplicate check-in prevention
    const { data: existingAttendance } = await admin
      .from("attendance")
      .select("id, status, check_in_time, method")
      .eq("gym_id", gym.id)
      .eq("member_id", member.id)
      .eq("attendance_date", today)
      .maybeSingle();

    if (existingAttendance && existingAttendance.status === "PRESENT") {
      return NextResponse.json({
        success: true,
        status: "ALREADY_CHECKED_IN",
        message: "You're already checked in today!",
        gymName: gym.name,
        checkInTime: existingAttendance.check_in_time,
        todayWorkout,
      });
    }

    // 7. Record Attendance
    const now = new Date().toISOString();
    const { data: newAttendance, error: attErr } = await admin
      .from("attendance")
      .upsert(
        {
          gym_id: gym.id,
          member_id: member.id,
          attendance_date: today,
          status: "PRESENT",
          method: "QR",
          check_in_time: now,
          recorded_by: user.id,
        },
        { onConflict: "gym_id,member_id,attendance_date" }
      )
      .select()
      .single();

    if (attErr) {
      return NextResponse.json({ error: attErr.message || "Failed to record attendance" }, { status: 500 });
    }

    const memberName = (member.profiles as any)?.full_name || "Athlete";

    return NextResponse.json({
      success: true,
      status: "CHECKED_IN",
      message: `Welcome to ${gym.name}, ${memberName}! Check-in confirmed.`,
      gymName: gym.name,
      checkInTime: now,
      todayWorkout,
    });
  } catch (err: any) {
    return NextResponse.json({ error: err.message || "Internal server error" }, { status: 500 });
  }
}
